[phases.setup]
nixPkgs = ['php82', 'php82Extensions.mysqli', 'php82Extensions.pdo', 'php82Extensions.pdo_mysql', 'composer']

[phases.install]
cmds = ['composer install --no-dev --prefer-dist', 'echo "PHP y Composer instalados correctamente"']

[start]
cmd = 'php -S 0.0.0.0:$PORT -t .'